* Геометрия

** Определения

*** Дифферецируемая функция

Бесконечно дифференцируемая (возможно многомерная) функция. В
численном представлении по запросу можем получить производную, которая
в свою очередь дифференцируема и максимум нормы дифференциала на
данной окрестности.

*** Многообразие

Дифференцируемое многообразие. Использование численных методов и
ограничения компьютерного представления накладывают дополнительные
требования на возможные функции и дополнительные свойства окрестностей
и атласов. Стараемся избегать численного интегрирования и
дифференцирования за счет требования дополнительной информации.

*** Пространство

Многообразие с локальным расстоянием. Для точек из одной окрестности
можно получить расстояние между ними. Должно отвечать на запрос о
диаметре окрестности и получение покрытия данного набора окрестностей
меньшего диаметра.

*** Геометрический объект

В некотором пространстве — множество точек пространства, такое что для
каждой окрестности пространства, объект в ней не существует либо
диффеоморфен конусу (существует диффеоморфизм окрестности стандартного
конуса в данную окрестность, такой что точки конуса и есть точки
объекта) либо устроен сложно. Предполагаем, что окрестность в которой
объект сложно устроен можно "измельчить" на кусочки, в которых объект
устроен просто или измельчить до необходимого уровня точности.

*** Конус

Нульмерный конус — точка.

Конус для положительных измерений — множество точек отрезков от центра
шара до сферы, такое что концы отрезков — геометрический объект на
сфере. Стандартный — с центром в нуле радиусом единица.

** Алгоритм

Варианты:

1. Задаем необходимую точность (погрешность) решения.
2. Общая идея — минимизируем не время решения задачи, а время принятия
   решения. Решение задачи — процесс последовательных (или в случае
   нескольких вариантов — параллельных) уточнений возможных ответов,
   так что можно постановку задачи уточнить или задачу прервать
   (текущее значение и будет ответом).

Собственно идея алгоритма:

1. Определяем область (окрестность) пространства, в котором будем
   решать задачу (по умолчанию всё пространство) — начальный набор
   окрестностей.
2. Предъявляем набор окрестностей геометрическому объекту для разметки
   на пустые, конусы и сложные.
3. По результатам решаем задачу локально. При необходимости выбираем
   окрестности (например сложные) для нового запроса, их измельчаем и
   переходим к п.2.

** Установки

1. Результат — пакет на языке Python в репозитории PyPi.
2. Язык комментариев и документации — английский.

** План

*** TODO Уточнение формулировки задачи [2/5]

- [X] Определить понятие вещественного числа. По умолчанию float, но
  важно иметь возможность работать с другими типами. Поэтому пока
  синоним.
- [X] Множество вещественных чисел — набор интервалов — пар
  вещественных чисел.
- [ ] Точка на единичной окружности. Задается парой вещественных чисел.
- [ ] Множество точек единичной окружности — набор пар точек на
  окружности. Множеству принадлежат точки, которые получаются
  вращением от первой ко второй против часовой стрелки.
- [ ] задача: Есть 2 целых числа X>=0 и Y>=0, не равные нулю
  одновременно. Найти неотрицательные x<=M и y<=M (где M положительное
  целое), такие что y/x < Y/X и y/x максимально.

*** DONE Множество вещественных чисел
Создать классы FloatInterval — интервал вещественных чисел и FloatSet —
множество вещественных чисел в файле floatset.py.
- интервал представляет собой tuple из двух чисел (левая и правая граница)
- пустой интервал — левая граница больше правой
- сделать операции по аналогии с множествами для интервалов.
  Результатом операции может быть несколько интервалов (tuple)
- Множество (FloatSet) представляется в виде tuple из отсортированных
  непересекающихся интервалов
- Сделать стандартные операции с множествами для FloatSet.
- Конструктор FloatSet должен принимать на входе произвольные числа и
  последовательности чисел или пар чисел.  Последовательности при
  входе должны нормализовываться.

*** DONE Углы, точки и множества на окружности
Создать файл floatcircle.py, в котором создать классы FloatAngle,
FloatCirklePoint, FloatCircleInterval, FloatCircleSet.
- объект FloatAngle задается числом типа float – углом в радианах в
  диапазоне [0,2pi], правая граница не включается. В конструкторе
  предусмотреть нормализацию.
- FloatCirklePoint задает точку на окружности соответствующим углом.
- FloatCircleInterval задает дугу на окружности парой точек, которая
  получается при движении от первой точки ко второй против часовой
  стрелки.
- FloatCircleSet - множество точек на окружности, задаваемое
  упорядоченным множеством непересекающихся интервалов.
Выполненная работа

Создан файл `floatcircle.py` в директории `/home/fva/geo/geo/` со следующими классами:

### 1. `FloatAngle`
- Представляет угол в радианах в диапазоне `[0, 2π)` (правая граница не включается)
- Конструктор выполняет нормализацию угла
- Реализованы арифметические операции, сравнение, методы для работы с углами
- Использует `math.nextafter` для определения максимального угла меньше `2π`

### 2. `FloatCirclePoint`
- Представляет точку на единичной окружности через угол
- Использует `FloatAngle` для хранения угла
- Методы для вращения, вычисления расстояния, преобразования в декартовы координаты

### 3. `FloatCircleInterval`
- Представляет дугу на окружности от первой точки ко второй против часовой стрелки
- Интервал от точки до самой себя представляет только эту точку (не пустой)
- Полный круг представляется как интервал от точки до `math.nextafter(точка, -math.inf)`
- Реализованы операции: проверка принадлежности точки, пересечение, объединение, дополнение

### 4. `FloatCircleSet`
- Представляет множество точек на окружности как упорядоченное множество непересекающихся интервалов
- Реализованы операции над множествами: объединение, пересечение, разность, симметрическая разность, дополнение

## Особенности реализации
- Не используются `math.isclose`, только точные сравнения и `math.nextafter`
- На окружности интервалы никогда не бывают пустыми (всегда содержат хотя бы начальную точку)
- Множества интервалов могут быть пустыми (не содержать интервалов)
- Учтена цикличность окружности при операциях с интервалами

Файл создан и готов к использованию в проекте геометрической библиотеки.

*** [8/11] Мелочи
- [X] Длина пустого интервала -inf.
- [X] Поправить скрипты и AGENTS.md
- [X] Интервал из точки и интервала
- [X] Множество из интервала и из точки
- [X] Sequence
- [X] Угол из float
- [ ] left right на start end
- [ ] union и difference для нескольких
- [ ] IntervalClass как параметр Set
- [X] Set from tuple
- [X] ValidTuple


** Для памяти

- Вещественные числа.
- Евклидово пространство. Размерность. Каноническая система координат.
- Риманово пространство. Размерность. Собственные координаты и
отображение в эвклидово окрестности. Локальное покрытие

** Скрипты

#+NAME: coverage
#+BEGIN_SRC shell :results value
  coverage run --branch --include="geo/*" -m unittest discover -s tests
#+END_SRC

#+RESULTS: coverage
: 0

#+NAME: coverage-html
#+BEGIN_SRC shell  :results value
  coverage html
#+END_SRC

#+RESULTS: coverage-html
: 0

#+NAME: docs-html
#+BEGIN_SRC shell :results value
  make -C doc html
#+END_SRC

#+RESULTS: docs-html
: 0

#+NAME: coverage-json
#+BEGIN_SRC shell  :results value
  coverage json
#+END_SRC

#+RESULTS: coverage-json
: 0


#+NAME: tests
#+BEGIN_SRC shell :results value
  python -m unittest discover -s tests
#+END_SRC

#+RESULTS: tests
: 0

#+NAME: doctest
#+BEGIN_SRC shell :results value
  python -m doctest -f README.rst
#+END_SRC

#+RESULTS: doctest
: 0

#+NAME: pylint
#+BEGIN_SRC shell :results output scalar
  pylint geo/**/*.py
#+END_SRC

#+RESULTS: pylint
: 
: --------------------------------------------------------------------
: Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
: 
