* Геометрия

** Определения

Геометрический объект в римановом пространстве — множество точек,
такое что для каждой точки существует окрестность в которой объект
диффеоморфен конусу.

Конус — множество точек отрезков от центра шара до сферы, такое что концы
отрезков — геометрический объект на сфере.

** Установки

1. Результат — пакет на языке Python в репозитории PyPi.
2. Язык комментариев и документации — английский.

** План

*** TODO Уточнение формулировки задачи [0/4]

- [ ] Определить понятие вещественного числа. По умолчанию float, но
  важно иметь возможность работать с другими типами. Поэтому пока
  синоним.
- [ ] Множество вещественных чисел — набор интервалов — пар
  вещественных чисел.
- [ ] Точка на единичной окружности. Задается парой вещественных чисел.
- [ ] Множество точек единичной окружности — набор пар точек на
  окружности. Множеству принадлежат точки, которые получаются
  вращением от первой ко второй против часовой стрелки.

*** DONE Множество вещественных чисел
Создать классы FloatInterval — интервал вещественных чисел и FloatSet —
множество вещественных чисел в файле floatset.py.
- интервал представляет собой tuple из двух чисел (левая и правая граница)
- пустой интервал — левая граница больше правой
- сделать операции по аналогии с множествами для интервалов.
  Результатом операции может быть несколько интервалов (tuple)
- Множество (FloatSet) представляется в виде tuple из отсортированных
  непересекающихся интервалов
- Сделать стандартные операции с множествами для FloatSet.
- Конструктор FloatSet должен принимать на входе произвольные числа и
  последовательности чисел или пар чисел.  Последовательности при
  входе должны нормализовываться.

*** TODO [1/5] Мелочи
- [ ] Длина пустого интервала -1.
- [X] Поправить скрипты и AGENTS.md
- [ ] Интервал из точки
- [ ] Множество из интервала и из точки
- [ ] Sequence


** Для памяти

- Вещественные числа.
- Евклидово пространство. Размерность. Каноническая система координат.
- Риманово пространство. Размерность. Собственные координаты и
отображение в эвклидово окрестности. Локальное покрытие

** Скрипты

#+NAME: coverage
#+BEGIN_SRC shell :results value
  coverage run --branch --include="geo/*" -m unittest discover -s tests
#+END_SRC

#+RESULTS: coverage
: 0

#+NAME: coverage-html
#+BEGIN_SRC shell  :results value
  coverage html
#+END_SRC

#+RESULTS: coverage-html
: 0

#+NAME: coverage-json
#+BEGIN_SRC shell  :results value
  coverage json
#+END_SRC

#+RESULTS: coverage-json
: 0


#+NAME: tests
#+BEGIN_SRC shell :results value
  python -m unittest discover -s tests
#+END_SRC

#+RESULTS: tests
: 0

#+NAME: doctest
#+BEGIN_SRC shell :results value
  python -m doctest -f README.rst
#+END_SRC

#+RESULTS: doctest
: 0

#+NAME: pylint
#+BEGIN_SRC shell :results output scalar
  pylint geo/**/*.py
#+END_SRC

#+RESULTS: pylint
: 
: --------------------------------------------------------------------
: Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
: 
