"""Public mathematical core of the package.

This module defines the intended public surface for the early-stage project.
It deliberately excludes notebook-global helpers and compatibility aliases.
"""

from .diffeomorphism import Chart, Diffeomorphism, InvertibleMap, Map
from .euclidean import (
    AffineDiffeomorphism,
    EuclideanChart,
    EuclideanNeighborhood,
    FloatPoint,
    FloatVector,
)
from .floatcircle import (
    FULL_FLOAT_CIRCLE_INTERVAL,
    FULL_FLOAT_CIRCLE_SET,
    FloatAngle,
    FloatCircleInterval,
    FloatCirclePoint,
    FloatCircleSet,
)
from .floatset import (
    ALL_FLOATS_INTERVAL,
    EMPTY_FLOAT_INTERVAL,
    FULL_FLOAT_INTERVAL,
    FloatInterval,
    FloatSet,
)
from .geometric import (
    Ball,
    ChartedGeometricObject,
    Circle,
    CirclePointObject,
    CircleSetObject,
    CircleSphereObject,
    Cone,
    Cube,
    CubeSurface,
    DirectionSetSphereObject,
    Ellipsoid,
    EllipsoidSurface,
    EuclideanCone,
    EuclideanPointObject,
    GeometricObject,
    HalfPlane,
    HalfSpace,
    Hyperplane,
    LocalConeModel,
    Parallelepiped,
    ParallelepipedSurface,
    PlanarAngle,
    RadialCone,
    RealLine,
    RealPointObject,
    RealSetObject,
    SmoothImageObject,
    Sphere,
    SphereObject,
    SphericalCone,
    WholePlane,
    WholeSpace,
)
from .manifold import (
    Atlas,
    ChartNeighborhood,
    ChartTransition,
    LocalObjectModel,
    Manifold,
    ManifoldChart,
    Neighborhood,
    NeighborhoodCover,
    NeighborhoodMarking,
    classify_local_object,
    classify_neighborhoods,
    refine_neighborhoods,
)
from .real import ALL_REALS_INTERVAL, EMPTY_REAL_INTERVAL, real, realset
from .operations import (
    RefinedObjectCover,
    classify_cover,
    local_chart_cover_from_points,
    refine_until,
)
from .riemannian import (
    ChartedMetricSpace,
    EuclideanMetricSpace,
    EuclideanPlaneSpace,
    LazyMetricExpressionObject,
    LazyMetricMappedObject,
    LazyMetricObject,
    MetricGeometricObject,
    MetricSpace,
    RealLineSpace,
    UnitCircleSpace,
)
from .space import Space, SpherePoint, SphereSpace, TorusPoint, TorusSpace
from .transform import (
    PointTransform,
    Transform,
    identity_transform,
    visualization_transform_2d,
    visualization_transform_3d,
)

CircleSpace = UnitCircleSpace

__all__ = [
    "real",
    "realset",
    "Map",
    "InvertibleMap",
    "Diffeomorphism",
    "Chart",
    "ChartTransition",
    "Atlas",
    "Neighborhood",
    "ChartNeighborhood",
    "NeighborhoodCover",
    "NeighborhoodMarking",
    "refine_neighborhoods",
    "LocalObjectModel",
    "classify_local_object",
    "classify_neighborhoods",
    "Cone",
    "SphereObject",
    "GeometricObject",
    "RealLine",
    "Circle",
    "WholeSpace",
    "Hyperplane",
    "HalfSpace",
    "Sphere",
    "Ball",
    "EllipsoidSurface",
    "Ellipsoid",
    "CubeSurface",
    "Cube",
    "ParallelepipedSurface",
    "Parallelepiped",
    "DirectionSetSphereObject",
    "CircleSphereObject",
    "EuclideanCone",
    "RadialCone",
    "SphericalCone",
    "LocalConeModel",
    "RefinedObjectCover",
    "ChartedGeometricObject",
    "SmoothImageObject",
    "RealPointObject",
    "CirclePointObject",
    "EuclideanPointObject",
    "RealSetObject",
    "CircleSetObject",
    "WholePlane",
    "HalfPlane",
    "PlanarAngle",
    "MetricSpace",
    "Space",
    "Transform",
    "PointTransform",
    "ChartedMetricSpace",
    "LazyMetricObject",
    "LazyMetricExpressionObject",
    "LazyMetricMappedObject",
    "MetricGeometricObject",
    "RealLineSpace",
    "CircleSpace",
    "UnitCircleSpace",
    "SpherePoint",
    "SphereSpace",
    "TorusPoint",
    "TorusSpace",
    "identity_transform",
    "visualization_transform_2d",
    "visualization_transform_3d",
    "EuclideanMetricSpace",
    "EuclideanPlaneSpace",
    "Manifold",
    "ManifoldChart",
    "FloatVector",
    "FloatPoint",
    "EuclideanNeighborhood",
    "EuclideanChart",
    "AffineDiffeomorphism",
    "local_chart_cover_from_points",
    "classify_cover",
    "refine_until",
    "ALL_REALS_INTERVAL",
    "EMPTY_REAL_INTERVAL",
    "FloatInterval",
    "FloatSet",
    "EMPTY_FLOAT_INTERVAL",
    "FULL_FLOAT_INTERVAL",
    "ALL_FLOATS_INTERVAL",
    "FloatAngle",
    "FloatCirclePoint",
    "FloatCircleInterval",
    "FloatCircleSet",
    "FULL_FLOAT_CIRCLE_INTERVAL",
    "FULL_FLOAT_CIRCLE_SET",
]
